name: K3s e2e tests

on:
  workflow_dispatch:  # Allow manual runs.
  pull_request:
    branches: ['main']

jobs:
  e2e-tests:
    name: e2e tests
    runs-on: macos-11

    env:
     LIMA_INSTANCE: "ko-k3s-demos"
     KO_DOCKER_REPO: "k3s.local"
     
    steps:
    - name: Install test dependencies
      run: brew install qemu bash coreutils lima

    - name: Install go v1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Check out Demo App
      uses: actions/checkout@v3
      with:
        path: './ko-demo-app'

    - name: Setup Lima k3s cluster Cluster
      run: |
        limactl start --tty=false ./ko-k3s-demos.yaml
        mkdir -p "$HOME/.lima/$LIMA_INSTANCE/conf"
        export KUBECONFIG="$HOME/.lima/$LIMA_INSTANCE/conf/kubeconfig.yaml"
        limactl shell "$LIMA_INSTANCE" sudo cat /etc/rancher/k3s/k3s.yaml >$KUBECONFIG
      working-directory: ko-demo-app
        
    - name: Install Kubectl
      uses: azure/setup-kubectl@v2.0

    - name: Checkout ko WIP
      uses: actions/checkout@v3
      with:
        repository: kameshsampath/ko
        ref: 'ko-k3s'
        path: './ko'
    
    - name: Check if k3s server is reachable
      run: |
        kubectl get pods

    - name: Install ko
      run: go install ./ko

    - name: Run Smoke Test
      run: |
        export KUBECONFIG="$HOME/.lima/$LIMA_INSTANCE/conf/kubeconfig.yaml"
        # Test with k3s load
        KO_DOCKER_REPO=k3s.local ko apply --platform=all -f ./configs
        kubectl rollout status deploy/myapp --timeout 30s
      working-directory: ko-demo-app
        
