name: K3s e2e tests

on:
  workflow_dispatch:  # Allow manual runs.
  pull_request:
    branches: ['main']

jobs:
  e2e-tests:
    name: e2e tests
    runs-on: macos-11

    env:
     LIMA_INSTANCE: "ko-k3s-demos"
     KO_DOCKER_REPO: "k3s.local"
     
    steps:
    - name: Install test dependencies
      run: |
       brew update
       brew install qemu bash coreutils lima jq
       brew upgrade

    - name: Install go v1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Check out Demo App
      uses: actions/checkout@v3
      with:
        path: './ko-demo-app'

    - name: Cache ~/Library/Caches/lima/download
      uses: actions/cache@v2
      with:
        path: ~/Library/Caches/lima/download
        key: ${{ runner.os }}-lima-cache
        
    - name: Setup Lima k3s cluster Cluster
      id: lima_vm
      run: |
        limactl start --tty=false ./ko-k3s-demos.yaml
        mkdir -p "$HOME/.lima/$LIMA_INSTANCE/conf"
        export KUBECONFIG="$HOME/.lima/$LIMA_INSTANCE/conf/kubeconfig.yaml"
        limactl shell "$LIMA_INSTANCE" sudo cat /etc/rancher/k3s/k3s.yaml >$KUBECONFIG
        echo "::set-output name=kubeconfig::$KUBECONFIG"
      working-directory: ko-demo-app

    - name: Install Kubectl
      uses: azure/setup-kubectl@v2.0

    - name: Sanity check to see if kubernetes cluster is reachable
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        retry_wait_seconds: 30
        max_attempts: 20
        command: ./ko-demo-app/hack/k3s-readiness-check.sh
      env:
        KUBECONFIG: "${{ steps.lima_vm.outputs.kubeconfig }}"


    - name: Checkout ko WIP
      uses: actions/checkout@v3
      with:
        repository: kameshsampath/ko
        ref: 'ko-k3s'
        path: './ko'
    
    - name: Install ko
      run: go install .
      working-directory: ko

    - name: Run Smoke Test
      run: |
        ko version
        ko apply -v -f ./configs
        kubectl rollout status deploy/myapp --timeout 30s
      env:
        KUBECONFIG: "${{ steps.lima_vm.outputs.kubeconfig }}"
        KO_DOCKER_REPO: k3s.local
      working-directory: ko-demo-app
        
